# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    ports:
      - 3306:3306
    environment:
# Usuário já é criado por default
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: devdojo
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo:

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080